# Generated by Django 5.0.2 on 2024-02-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0003_user_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
    ]
