# Generated by Django 5.0.2 on 2024-02-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0004_remove_user_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'superuser'), (1, 'admin'), (2, 'doctor'), (3, 'nurse'), (4, 'patient'), (5, 'external')], null=True),
        ),
    ]
