# Generated by Django 5.0.2 on 2024-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'superuser'), (1, 'admin'), (2, 'doctor'), (3, 'nurse'), (4, 'external'), (5, 'patient')], null=True),
        ),
    ]
