# Generated by Django 5.0.2 on 2024-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SUPERUSER'), (1, 'ADMIN'), (2, 'DOCTOR'), (3, 'NURSE'), (4, 'EXTERNAL'), (5, 'PATIENT')], default=0),
        ),
    ]
