# Generated by Django 5.0.2 on 2024-04-04 16:42

from django.db import migrations

def create_default_payrates(apps, schema_editor):
    PayRate = apps.get_model("smartcare_auth", "PayRate")
    payrates = [
        PayRate(title="doctor", rate=40.0),
        PayRate(title="nurse", rate=20.0),
        PayRate(title="nurse practitioner", rate=30.0)
    ]
    for payrate in payrates:
        payrate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0012_payrate'),
    ]

    operations = [
        migrations.RunPython(create_default_payrates),
    ]
