# Generated by Django 5.0.2 on 2024-04-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0013_auto_20240404_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='payrate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payrate', to='smartcare_auth.payrate'),
        ),
    ]
