# Generated by Django 5.0.2 on 2024-04-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0011_patient'),
        ('smartcare_auth', '0014_staff_payrate'),
    ]

    operations = [
    ]
