# Generated by Django 5.0.2 on 2024-04-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0015_merge_0011_patient_0014_staff_payrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
