# Generated by Django 5.0.2 on 2024-04-30 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0019_user_address_line_1_user_address_line_2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^[\\d- ]*$', 'Phone numbers cannot contain values other than digits and hyphens'), django.core.validators.MinLengthValidator(3, 'Phone numbers must be atleast 3 digits long')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, 'City/Town field cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^\\D+$', 'City/Town names cannot include digits'), django.core.validators.MinLengthValidator(1, 'City/Town field cannot be empty')]),
        ),
    ]
