# Generated by Django 5.0.2 on 2024-05-01 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_auth', '0020_user_phone_number_alter_user_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^[\\d -]*$', 'Phone numbers cannot contain values other than digits and hyphens'), django.core.validators.MinLengthValidator(3, 'Phone numbers must be atleast 3 digits long')]),
        ),
    ]
