version: '3.8'

services:
  web:
    build: ./smartcare_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./smartcare_django/:/usr/src/smartcare_django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --port=8080
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - 8080:8080
    environment:
      - MYSQL_ROOT_PASSWORD=greenlaughingspanielcremation
      - MYSQL_USER=smartcare
      - MYSQL_PASSWORD=smartcare
      - MYSQL_DATABASE=smartcare

volumes:
  mysql_data: