# Generated by Django 5.0.2 on 2024-03-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0002_appointment_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='reason',
        ),
    ]
