# Generated by Django 5.0.2 on 2024-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0003_rename_notes_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptom_duration',
            field=models.IntegerField(default=1),
        ),
    ]
