# Generated by Django 5.0.2 on 2024-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0005_alter_appointment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot_number',
            field=models.IntegerField(default=-1),
        ),
    ]
