# Generated by Django 5.0.2 on 2024-03-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0008_holiday_workingdays_delete_nonworkingdays'),
        ('smartcare_auth', '0011_staff_remove_user_employment_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkingDays',
            new_name='WorkingDay',
        ),
    ]
