# Generated by Django 5.0.2 on 2024-03-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0009_rename_workingdays_workingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingday',
            name='is_active',
        ),
    ]
