# Generated by Django 5.0.2 on 2024-03-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0011_remove_holiday_date_holiday_end_date_and_more'),
        ('smartcare_auth', '0011_staff_remove_user_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('reason', models.CharField(blank=True, default='Holiday', max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='smartcare_auth.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
