# Generated by Django 5.0.2 on 2024-03-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0012_timeoff_delete_holiday'),
        ('smartcare_auth', '0011_staff_remove_user_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeOff', to='smartcare_auth.staff'),
        ),
    ]
