# Generated by Django 5.0.2 on 2024-03-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0013_alter_timeoff_staff'),
        ('smartcare_auth', '0011_staff_remove_user_employment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeoff',
            unique_together={('staff', 'start_date', 'end_date')},
        ),
    ]
