# Generated by Django 5.0.2 on 2024-04-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0015_rename_time_slot_appointment_time_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reason',
            new_name='symptoms',
        ),
    ]
