# Generated by Django 5.0.2 on 2024-04-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0007_prescription_patient_prescription_staff_and_more'),
        ('smartcare_appointments', '0017_appointment_date_requested_alter_appointment_stage_and_more'),
    ]

    operations = [
    ]
