# Generated by Django 5.0.2 on 2024-04-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0018_appointmentcomment'),
        ('smartcare_appointments', '0018_merge_20240404_2214'),
    ]

    operations = [
    ]
