# Generated by Django 5.0.2 on 2024-04-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0019_merge_20240412_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentcomment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_comments', to='smartcare_appointments.appointment'),
        ),
    ]
