# Generated by Django 5.0.2 on 2024-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0020_alter_appointmentcomment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_by',
            field=models.IntegerField(choices=[(0, 'PATIENT'), (1, 'NHS')], default=None, null=True),
        ),
    ]
