# Generated by Django 5.0.2 on 2024-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0021_appointment_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
