# Generated by Django 5.0.2 on 2024-04-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0022_appointment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
