# Generated by Django 5.0.2 on 2024-04-29 15:18

import smartcare_appointments.models.appointment_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0023_alter_appointment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stage',
            field=models.IntegerField(choices=[(0, 'REQUESTED'), (1, 'APPROVED'), (2, 'SCHEDULED'), (3, 'COMPLETED'), (4, 'CANCELLED')], default=smartcare_appointments.models.appointment_models.AppointmentStage['REQUESTED']),
        ),
    ]
