# Generated by Django 5.0.2 on 2024-05-02 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0025_appointment_staff_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_request', to='smartcare_appointments.prescription'),
        ),
    ]
