from smartcare_appointments.views.appointment_views import AppointmentView
from smartcare_appointments.views.schedule_views import TimeOffView
from smartcare_appointments.views.prescription_views import PrescriptionsView