from smartcare_appointments.models.appointment_models import TimeSlot, AppointmentStage, Appointment
from smartcare_appointments.models.prescriptions_models import Prescription, PrescriptionRequest
from smartcare_appointments.models.schedule_models import WorkingDay, TimeOff