# Generated by Django 5.0.2 on 2024-04-04 12:30

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0014_alter_timeoff_unique_together'),
        ('smartcare_finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_appointment', to='smartcare_appointments.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
