# Generated by Django 5.0.2 on 2024-04-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_appointments', '0014_alter_timeoff_unique_together'),
        ('smartcare_finance', '0003_alter_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_appointment', to='smartcare_appointments.appointment'),
        ),
    ]
