# Generated by Django 5.0.2 on 2024-04-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_finance', '0004_alter_invoice_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
    ]
